parameters:
    pim_catalog.converter.metric.class: Akeneo\Pim\Enrichment\Component\Product\Converter\MetricConverter

services:
    pim_catalog.converter.metric:
        class: '%pim_catalog.converter.metric.class%'
        arguments:
            - '@akeneo_measure.measure_converter'
            - '@pim_catalog.builder.entity_with_values'
            - '@pim_catalog.repository.attribute'
